//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public string ReceiptID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<double> Total { get; set; }
        public string PersonID { get; set; }
        public string CustomerID { get; set; }
        public string ReceiptDetailID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Person Person { get; set; }
        public virtual Receipt_Detail Receipt_Detail { get; set; }
    }
}
