//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revenue
    {
        public string RevenueID { get; set; }
        public string ReceiptDetailID { get; set; }
        public Nullable<double> Expenses { get; set; }
        public double GrossRevenue { get; set; }
        public Nullable<double> Profit { get; set; }
    
        public virtual Receipt_Detail Receipt_Detail { get; set; }
    }
}
