//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreImportDetail
    {
        public string StoreImportDetailID { get; set; }
        public string StoreImportID { get; set; }
        public string ProductID { get; set; }
        public Nullable<int> ImportQuantity { get; set; }
    
        public virtual Store_Import Store_Import { get; set; }
        public virtual Product Product { get; set; }
    }
}
